# Generated by Django 2.2.6 on 2020-10-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectreviews', '0003_auto_20201026_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
